
const CAR_HEIGHT=120
const MAP_HEIGHT = 800;
const CAR_SRC='image/car.png'
const CAR_TOP=MAP_HEIGHT-CAR_HEIGHT
const MAP_TOP = 0;
const MAP_LEFT = 300;
const MAP_WIDTH = 450;
const NUMBER_OF_LANES=5
const CAR_WIDTH=MAP_WIDTH/NUMBER_OF_LANES
const LANE_WIDTH= MAP_WIDTH/NUMBER_OF_LANES;
const CAR_SPEED=MAP_WIDTH/NUMBER_OF_LANES
const LANE_SRC='image/lane.jpg'
const OBSTACLE_SPEED=3
const OBSTACLE_WIDTH=MAP_WIDTH/NUMBER_OF_LANES
const OBSTACLE_HEIGHT=MAP_WIDTH/NUMBER_OF_LANES
const NUMBER_OF_OBSTACLES=5